const projects = [
  {
    id: 1,
    name: 'Informatie',
    info: 'During the first period of my education, we created a website using HTML and CSS to inform parents about the school and the course during the parent evening.',
    gitLink: 'https://github.com/lisamast/ouderavond-project',
    imageUrl1: './images/informatie1.png',
    imageUrl2: './images/informatie1.png',
    imageUrl3: './images/informatie2.png',
  },
  {
    id: 2,
    name: 'Javascript game',
    info: 'In the second period of the program, we started working with JavaScript. We used it to create a game on a website. To further practice with HTML and CSS, we also worked out a social problem within the website.',
    gitLink: 'https://github.com/TechniekCollegeRotterdam/project-games-for-good-sod1a-antillen',
    imageUrl1: './images/game1.png',
    imageUrl2: './images/game1.png',
    imageUrl3: './images/game2.png',
  },
  {
    id: 3,
    name: 'Escaperoom',
    info: 'In the third period we combined HTML, CSS, JavaScript and PHP to create an escape room.',
    gitLink: 'https://github.com/TechniekCollegeRotterdam/project-escape-room-project-p3-escaperoom',
    imageUrl1: './images/escaperoom1.png',
    imageUrl2: './images/escaperoom1.png',
    imageUrl3: './images/escaperoom2.png',
  },
  {
    id: 4,
    name: 'Webshop',
    info: 'In the last period of the first year, we mainly worked with PHP and SQL, which we used to create a bakery webshop.',
    gitLink: 'https://github.com/TechniekCollegeRotterdam/projectp4-crud-login-sod1a-cvba',
    imageUrl1: './images/webshop1.png',
    imageUrl2: './images/webshop1.png',
    imageUrl3: './images/webshop2.png',
  },
  {
    id: 5,
    name: 'App design',
    info: 'For my first optional subjects I created an app for an Italian restaurant in Figma.',
    imageUrl1: './images/appdesign.png',
    imageUrl2: './images/appdesign1.png',
    imageUrl3: './images/appdesign2.png',
    imageUrl4: './images/appdesign3.png',
  },
    {
    id: 5,
    name: 'OOP project',
    info: 'My first OOP project was also my first project in my second year. I created a website for a fictional theater.',
    gitLink: 'https://gitlab.com/techniek-college-rotterdam/schiedam/2026/projects/oop-lisa-mischa/oopproject',
    imageUrl1: './images/oop-1.png',
    imageUrl2: './images/oop-2.png',
  },
    {
    id: 5,
    name: 'Offtrack',
    info: 'For my last optional subject I worked with React Native to create a mobile app where people could log their trips. This was for practicing.',
    gitLink: 'https://github.com/lisamast/OffTrack',
    imageUrl1: './images/offtrack.png',
    imageUrl2: './images/offtrack1.png',
    imageUrl3: './images/offtrack2.png',
    imageUrl4: './images/offtrack3.png',
    imageUrl5: './images/offtrack4.png',
  },
    {
    id: 5,
    name: 'Docenten lunch app',
    info: 'For my last optional subject I created an app for teachers to order lunch at school. I made this app in React Native for my exam.',
    gitLink: 'https://github.com/lisamast/Docentenlunch',
    imageUrl1: './images/lunch.jpg',
    imageUrl2: './images/lunch1.jpg',
    imageUrl3: './images/lunch2.jpg',
    imageUrl4: './images/lunch3.jpg',
    imageUrl5: './images/lunch4.jpg',

  },
    {
    id: 5,
    name: 'Barbershop',
    info: 'The last project I made in my second year was for my practice exam. I created a website for a fictional barbershop. I used Next.js for this project.',
    gitLink: 'https://github.com/lxuiejane/Barbershop-Examen',
    imageUrl1: './images/barber1.png',
    imageUrl2: './images/barber2.png',
  },

];

export default projects;
